Controllers/DicasController.cs
using HustleCastle.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using HustleCastle.Data;
using Microsoft.AspNetCore.Authorization;

namespace HustleCastle.Controllers
{
    [Authorize]
    public class DicasController : Controller
    {
        private readonly SheetsDatabase _sheetsDatabase;

        public DicasController(SheetsDatabase sheetsDatabase)
        {
            _sheetsDatabase = sheetsDatabase;
        }
        [AllowAnonymous]
        public ActionResult Index()
        {
            IList<Tutorial> tutorials = _sheetsDatabase.GetAll<Tutorial>();
            return View(tutorials);
        }

        [AllowAnonymous]
        public ActionResult Detalhes(int id)
        {
            Tutorial tutorial = _sheetsDatabase.GetByID<Tutorial>(id);
            return View(tutorial);
        }

        // GET: TutorialsController/Create
        public ActionResult Criar()
        {
            Tutorial tutorial = new Tutorial();
            return View("Editar", tutorial);
        }

        // GET: TutorialsController/Edit/5
        public ActionResult Editar(int id)
        {
            Tutorial tutorial = _sheetsDatabase.GetByID<Tutorial>(id);
            return View("Editar", tutorial);
        }


        [HttpPost]
        public ActionResult Save(Tutorial tutorial)
        {
            if (ModelState.IsValid)
            {
                if (tutorial.ID == 0)
                {
                    tutorial.CreatedAt = DateTime.UtcNow.AddHours(-3).ToString();
                    _sheetsDatabase.Add<Tutorial>(tutorial);
                    Audit audit = new Audit(User.Identity.Name, "Create", nameof(Tutorial), tutorial.Title);
                    _sheetsDatabase.Add<Audit>(audit);
                }
                else
                {
                    _sheetsDatabase.Update<Tutorial>(tutorial);
                    Audit audit = new Audit(User.Identity.Name, "Edit", nameof(Tutorial), tutorial.Title);
                    _sheetsDatabase.Add<Audit>(audit);
                }
                return RedirectToAction(nameof(Index));
            }

            return View(nameof(Editar), tutorial);

        }

        // GET: TutorialsController/Delete/5
        public ActionResult Excluir(int id)
        {
            _sheetsDatabase.Delete<Tutorial>(id);
            Audit audit = new Audit(User.Identity.Name, nameof(Excluir), nameof(Tutorial), id.ToString());
            _sheetsDatabase.Add<Audit>(audit);
            return RedirectToAction(nameof(Index));
        }

        // POST: TutorialsController/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Controllers/TutoriaisController.cs
using HustleCastle.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using HustleCastle.Data;

namespace HustleCastle.Controllers
{
    public class TutoriaisController : Controller
    {
        private readonly SheetsDatabase sheetsDatabase;
        private readonly IWebHostEnvironment _hostingEnvironment;

        public TutoriaisController(IWebHostEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            var a = Path.Combine(_hostingEnvironment.ContentRootPath, "client_secret.json");
            using (var stream = new FileStream(a, FileMode.Open, FileAccess.Read))
            {
                sheetsDatabase = new SheetsDatabase("Teste", "1VKcGHaNzCU6dH9MNMEnlxfcb5sX7fM2t1G8OblestPg", stream);
            }
        }
        // GET: TutorialsController
        public ActionResult Index()
        {
            IList<Tutorial> tutorials = sheetsDatabase.GetAll<Tutorial>();
            return View(tutorials);
        }

        // GET: TutorialsController/Details/5
        public ActionResult Detalhes(int id)
        {
            Tutorial tutorial = sheetsDatabase.GetByID<Tutorial>(id);
            return View(tutorial);
        }

        // GET: TutorialsController/Create
        public ActionResult Criar()
        {
            Tutorial tutorial = new Tutorial();
            return View("Editar", tutorial);
        }

        // GET: TutorialsController/Edit/5
        public ActionResult Editar(int id)
        {
            Tutorial tutorial = sheetsDatabase.GetByID<Tutorial>(id);
            return View("Editar", tutorial);
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(Tutorial tutorial)
        {
            try
            {
                if (tutorial.ID == 0)
                {
                    tutorial.CreatedAt = DateTime.Now.ToString();
                    
                    sheetsDatabase.Add<Tutorial>(tutorial);
                }
                else
                {
                    sheetsDatabase.Update<Tutorial>(tutorial);
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View("Editar", tutorial);
            }
        }

        // GET: TutorialsController/Delete/5
        public ActionResult Excluir(int id)
        {
            sheetsDatabase.Delete<Tutorial>(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: TutorialsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/Shared/_Layout - Copy.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HustleCastle Brasil Ceará</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HustleCastle Brasil Ceará</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark"  asp-controller="Tutoriais" asp-action="Index">Tutoriais</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - HustleCastle - Brasil Ceará
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Brasil Ceará</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/1.10.20/css/dataTables.bootstrap4.min.css" rel="stylesheet" crossorigin="anonymous" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/js/all.min.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <a class="navbar-brand" href="index.html">Brasil Ceará</a>
        <button class="btn btn-link btn-sm order-1 order-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ml-auto mr-0 mr-md-3 my-2 my-md-0">
        </form>
        <div class="text-light">@User.Identity.Name </div>
        <!-- Navbar-->
        @*<ul class="navbar-nav ml-auto ml-md-0">
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" id="userDropdown" href="#!" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><i class="fas fa-user fa-fw"></i></a>

                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#">Sair</a>
                </div>
            </li>
        </ul>*@
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <a class="nav-link nav-link-active" asp-controller="Home" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-home"></i></div>
                            Início
                        </a>
                        <a class="nav-link nav-link-active" asp-controller="Dicas" asp-action="Index">
                            <div class="sb-nav-link-icon"><i class="fas fa-book-open"></i></div>
                            Dicas
                        </a>
                        @if (User.Identity.IsAuthenticated)
                        {
                        <a class="nav-link nav-link-active" asp-controller="Home" asp-action="Logout">
                            <div class="sb-nav-link-icon"><i class="fas fa-user fa-fw"></i></div>
                            Logout
                        </a>
                         }
                        else
                        {
                        <a class="nav-link nav-link-active" asp-controller="Home" asp-action="Login">
                            <div class="sb-nav-link-icon"><i class="fas fa-user fa-fw"></i></div>
                           Login
                        </a>
                        }

                    </div>
                </div>
                @*<div class="sb-sidenav-footer">
                        <div class="small">Logged in as:</div>
                        Start Bootstrap
                    </div>*@
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid p-1">
                    @RenderBody()
                </div>
            </main>
            <footer class="border-top footer text-muted">
                <div class="container">
                    &copy; 2021 - HustleCastle - Brasil Ceará
                </div>
            </footer>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    @*<script src="~/lib/demo/chart-area-demo.js"></script>
    <script src="~/lib/demo/chart-bar-demo.js"></script>*@
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/dataTables.bootstrap4.min.js" crossorigin="anonymous"></script>
    <script src="~/lib/demo/datatables-demo.js"></script>
    <script src="~/js/scripts.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>